from django.urls import path
from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/add/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/edit/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('inventory/history/', views.InventoryHistoryView.as_view(), name='inventory_history'),
    path('inventory/bulk-restock/', views.BulkRestockView.as_view(), name='bulk_restock'),
    path('movement/add/', views.MovementCreateView.as_view(), name='movement_create'),
    path('movement/<int:pk>/edit/', views.MovementUpdateView.as_view(), name='movement_update'),
    path('sales/', views.SalesHistoryView.as_view(), name='sales_history'),
    path('sales/add/', views.SaleCreateView.as_view(), name='sale_create'),
    path('sales/<int:pk>/update/', views.SaleUpdateView.as_view(), name='sale_update'),
    path('sales/<int:pk>/delete/', views.SaleDeleteView.as_view(), name='sale_delete'),
    path('sales/<int:pk>/receipt/', views.ReceiptPDFView.as_view(), name='receipt_pdf'),
    path('money/', views.MoneyJournalView.as_view(), name='money_journal'),
    path('money/add/', views.MoneyJournalCreateView.as_view(), name='money_create'),
    path('money/<int:pk>/delete/', views.MoneyJournalDeleteView.as_view(), name='money_delete'),
    path('profit-report/', views.ProfitReportView.as_view(), name='profit_report'),
    path('reports/sales/', views.SalesReportView.as_view(), name='sales_report'),
    path('reports/expenses/', views.ExpensesReportView.as_view(), name='expenses_report'),
    path('categories/', views.ExpenseCategoryListView.as_view(), name='category_list'),
    path('categories/add/', views.ExpenseCategoryCreateView.as_view(), name='category_create'),
    path('low-stock/', views.LowStockView.as_view(), name='low_stock'),
    path('clients/', views.ClientListView.as_view(), name='client_list'),
    path('clients/add/', views.ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/', views.ClientDetailView.as_view(), name='client_detail'),
    path('debts/add/', views.DebtPaymentCreateView.as_view(), name='debt_payment_create'),
    path('debts/<int:pk>/delete/', views.DebtPaymentDeleteView.as_view(), name='debt_payment_delete'),
    path('products/<int:pk>/quick-stock/', views.quick_stock_update, name='quick_stock_update'),
    path('invoices/', views.InvoiceListView.as_view(), name='invoice_list'),
    path('invoices/new/', views.InvoiceCreateView.as_view(), name='invoice_create'),
    path('invoices/<int:pk>/edit/', views.InvoiceUpdateView.as_view(), name='invoice_update'),
    path('invoices/<int:pk>/delete/', views.InvoiceDeleteView.as_view(), name='invoice_delete'),
    path('invoices/<int:pk>/receipt/', views.InvoiceReceiptPDFView.as_view(), name='invoice_receipt_pdf'),
    path('api/product-by-barcode/<str:barcode>/', views.product_by_barcode, name='product_by_barcode'),
]
