# Generated by Django 6.0.1 on 2026-02-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_expensecategory_moneyjournal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='shop.sale'),
        ),
        migrations.AddField(
            model_name='moneyjournal',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='shop.sale'),
        ),
    ]
