# Generated by Django 6.0.1 on 2026-02-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_inventorymovement_sale_moneyjournal_sale'),
    ]

    def cleanup_legacy_sales(apps, schema_editor):
        MoneyJournal = apps.get_model('shop', 'MoneyJournal')
        InventoryMovement = apps.get_model('shop', 'InventoryMovement')
        # We can't use Q objects directly in migrations as easily with apps.get_model, 
        # but we can filter normally.
        
        # 1. Cleanup Reversal Expenses
        reversals = MoneyJournal.objects.filter(description__startswith="Reversal: Deleted Sale")
        for rev in reversals:
            # parsing: "Reversal: Deleted Sale of {product.name} (x{sale.quantity})"
            original_desc_part = rev.description.replace("Reversal: Deleted ", "")
            
            # Find and delete original income
            MoneyJournal.objects.filter(
                entry_type='Income',
                amount=rev.amount,
                description=original_desc_part
            ).delete()
            
            # Delete the reversal itself
            rev.delete()

        # 2. Cleanup Inventory Reversals
        # Reference format: "Sale Deleted (ID: {sale.id})"
        import re
        inv_reversals = InventoryMovement.objects.filter(reference__startswith="Sale Deleted (ID:")
        for inv_rev in inv_reversals:
            match = re.search(r'ID: (\d+)', inv_rev.reference)
            if match:
                sale_id = match.group(1)
                original_ref = f"Sale ID: {sale_id}"
                InventoryMovement.objects.filter(reference=original_ref).delete()
            inv_rev.delete()

    operations = [
        migrations.RunPython(cleanup_legacy_sales),
    ]
