# Generated by Django 6.0.1 on 2026-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_client_sale_amount_paid_sale_is_credit_sale_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
