# Generated by Django 6.0.1 on 2026-03-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_sale_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
