# Generated by Django 6.0.1 on 2026-03-14 19:03

from django.db import migrations, models


def set_remaining_quantities(apps, schema_editor):
    """
    Set remaining_quantity for existing inventory movements:
    - For IN movements: remaining_quantity = quantity (all stock available)
    - For OUT movements: remaining_quantity = 0 (no stock available)
    """
    InventoryMovement = apps.get_model('shop', 'InventoryMovement')
    
    # Set remaining_quantity for IN movements
    InventoryMovement.objects.filter(
        movement_type='IN'
    ).update(remaining_quantity=models.F('quantity'))
    
    # Set remaining_quantity for OUT movements
    InventoryMovement.objects.filter(
        movement_type='OUT'
    ).update(remaining_quantity=0)


def reverse_set_remaining_quantities(apps, schema_editor):
    """
    Reverse function: set remaining_quantity to 0 for all movements
    """
    InventoryMovement = apps.get_model('shop', 'InventoryMovement')
    InventoryMovement.objects.all().update(remaining_quantity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_inventorymovement_remaining_quantity'),
    ]

    operations = [
        migrations.RunPython(set_remaining_quantities, reverse_set_remaining_quantities),
    ]
