# Generated by Django 6.0.1 on 2026-03-14 19:11

from django.db import migrations, models


def populate_sale_cost_prices(apps, schema_editor):
    """
    Populate cost_price for existing sales using FIFO logic
    """
    Sale = apps.get_model('shop', 'Sale')
    InventoryMovement = apps.get_model('shop', 'InventoryMovement')
    Product = apps.get_model('shop', 'Product')
    
    # Get all sales without cost_price, ordered by date
    sales_without_cost = Sale.objects.filter(cost_price__isnull=True).order_by('date')
    
    for sale in sales_without_cost:
        # Calculate FIFO cost price at the time of sale
        # Get stock-in movements available before this sale date
        available_movements = InventoryMovement.objects.filter(
            product_id=sale.product_id,
            movement_type='IN',
            cost_price__isnull=False,
            date__lte=sale.date
        ).order_by('date')
        
        if available_movements:
            # Calculate FIFO cost based on available movements
            total_cost = 0
            remaining_quantity = sale.quantity
            
            for movement in available_movements:
                if remaining_quantity <= 0:
                    break
                
                # Calculate how much we can take from this batch
                batch_quantity = min(remaining_quantity, movement.quantity)
                total_cost += batch_quantity * movement.cost_price
                remaining_quantity -= batch_quantity
            
            if sale.quantity - remaining_quantity > 0:
                fifo_cost = total_cost / (sale.quantity - remaining_quantity)
                sale.cost_price = fifo_cost
                sale.save()
        else:
            # Fallback to product's base cost price
            product = Product.objects.get(pk=sale.product_id)
            if product.cost_price:
                sale.cost_price = product.cost_price
                sale.save()


def reverse_populate_sale_cost_prices(apps, schema_editor):
    """
    Reverse function: set cost_price to None for all sales
    """
    Sale = apps.get_model('shop', 'Sale')
    Sale.objects.all().update(cost_price=None)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_update_remaining_quantities'),
    ]

    operations = [
        migrations.RunPython(populate_sale_cost_prices, reverse_populate_sale_cost_prices),
    ]
