# Generated by Django 6.0.4 on 2026-07-02 09:47

from django.db import migrations


def uppercase_product_names(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        if product.name != product.name.upper():
            product.name = product.name.upper()
            product.save(update_fields=['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_inventorymovement_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(uppercase_product_names),
    ]
